### PR TITLE
Fix app.json

### PR DESCRIPTION
**Pull request by raulb**

### CODE REVIEW

**Comment by raulb** [comment]
@ukd1 These 2 changes should fix your issue with Heroku Button. Let me know how it goes cc @friism

**Comment by ukd1** [comment]
Thanks!!!

On Thursday, August 28, 2014, Raul Barroso notifications@github.com wrote:

> @ukd1 https://github.com/ukd1 These 2 changes should fix your issue
> with Heroku Button. Let me know how it goes cc @friism
> https://github.com/friism
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rainforestapp/fourchette-app/pull/2#issuecomment-53829505
> .

## 

Russ
Rainforest  |  +1-650-919-3216 |  rainforestqa.com

**Comment by jipiboily** [comment]
Well, this way the sentry plugin is paid, which makes Fourchette 24$/month. Not sure this is required. My 2 cents :)

**Comment by friism** [comment]
There's no free sentry plan: https://addons.heroku.com/sentry

If you want the deployed fourchette apps to be free, you should find a way to make it work without that add-on.

**Comment by jipiboily** [comment]
I actually removed all addons this morning as it felt it was useless friction. https://github.com/rainforestapp/fourchette-app/commit/f8126e696b872c041f05166efbc35ed4b512238e

**Comment by friism** [comment]
+1!

**Pull request merged**
